bag/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('/remove/<item_id>/', views.remove_from_bag, name='remove_from_bag')

]

boutique_ado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>', views.delete_product, name='delete_product'),

]

checkout/models.py
import uuid #used to create order number

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from profiles.models import UserProfile
from products.models import Product


# Create your models here.

class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False) #basic character field, max lent 32char, created automatically, cannot be edited
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True,
                                     blank=True, related_name='orders') # use models.SET_NULL if the profile is deleted since that will allow us to keep an order history in the admin even if the user is deleted.
    full_name = models.CharField(max_length=50, null=False, blank=False) # name chat field, 50 char, required
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True) # null and false true as not mandatory
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)  # address 1 mandatory
    street_address2 = models.CharField(max_length=80, null=True, blank=True) # address 2 not mandatory
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True) #add date and timestamp to purchases
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default="")
    stripe_pid = models.CharField(max_length=24, null=False, blank=False, default="")



    def _generate_order_number(self): #underscore before generate is a convention that indicates that this method is only used in this class
        """
        generates a random unique order number using UUID  (uuid4 is used for random 32 hex string)
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        update grand total each time line item is added, accounting for delivery costs
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE/100
        else: 
            self.delivery_cost = 0
            
        self.grand_total = self.order_total + self.delivery_cost
        self.save()
        """
        The way this works is by using the sum function across all the line-item total fields for all line items on this order.
        The default behaviour is to add a new field to the query set called line-item total sum.
        Which we can then get and set the order total to that.
        """
        

    def save(self, *args, **kwargs):
        """
        override the original save method to set the order number if it hasnt been set
        """
        if not self.order_number: #if no order number exists
            self.order_number = self._generate_order_number() #call _generate function to creat one
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number
    

class OrderLineItem(models.Model):
    """A line-item will be like an individual shopping bag item. Relating to a specific order
    And referencing the product itself. The size that was selected. The quantity.
    And the total cost for that line item.
    The basic idea here. Is when a user checks out.
    We'll first use the information they put into the payment form to create an order instance.
    And then we'll iterate through the items in the shopping bag.
    Creating an order line item for each one. Attaching it to the order.
    And updating the delivery cost, order total, and grand total along the way."""

    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems') #There's a foreign key to the order. With a related name of line items.So when accessing orders we'll be able to make calls such as order.lineitems.all and order.lineitems.filter
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE) #There's also a foreign key to the product for this line item.So that we can access all the fields of the associated product as well.
    product_size = models.CharField(max_length=2, null=True, blank=True) #XS,S,M,L,XL sizes, can be left blank as not all products have sizes
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)
    

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

    
    

products/models.py
from django.db import models

# Create your models here.

class Category(models.Model): #model for categories

    class Meta: 
        verbose_name_plural = 'Categories' #update the plural spelling of Category model in Admin view
    
    name = models.CharField(max_length=254) #name used for programmatic purposes
    friendly_name = models.CharField(max_length=254, null=True, blank=True) # 'friendly' name to use to display for example to customers
    
    
    
    def __str__(self):
        '''
        A Python “magic method” that returns a string representation of any object.
        This is what Python and Django will use whenever a model instance needs to be coerced and displayed as a plain string.
        Most notably, this happens when you display an object in an interactive console or in the admin.
        You’ll always want to define this method; the default isn’t very helpful at all.
        '''
        return self.name 
       

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL) #foreign key to a category model
    sku = models.CharField(max_length=254, blank=True, null=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2) 
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)


    def __str__(self):
        return self.name 

products/forms.py
from django import forms
from .models import Product, Category
from .widgets import CustomClearableFileInput

class ProductForm(forms.ModelForm):


    class Meta:
        model = Product
        fields = '__all__' #special dunder or double underscore string called all which will include all the fields.

    
    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories] #This special syntax is called the list comprehension.And is just a shorthand way of creating a for loop that adds items to a list

        self.fields['category'].choices =  friendly_names #Now that we have the friendly names, let's update the category field on the form.To use those for choices instead of using the id.
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse 
from django.contrib import messages
from .models import Product, Category
from django.db.models import Q #special object used to generate a search query ##find info in the queries portion of django docs
from django.db.models.functions import Lower
from .forms import ProductForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def all_products(request):
    '''a view to return all products, including sorting and search queries'''

    products = Product.objects.all() #return all products from database
    query = None #start with empty query so we dont get error on products page without a search term
    categories = None #starting with empty for same reason as above
    sort = None #starting with empty for same reason as above
    direction = None #starting with empty for same reason as above

    if request.GET: #if we receive a request.get from form
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if 'sortkey' == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if 'sortkey' == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET: #checking if category exists in request.get
            categories = request.GET['category'].split(',') # create variable with request.get content and split list from comma
            products = products.filter(category__name__in=categories) #And then use that list to filter the current query set of all products down to only products whose category name is in the list.
            categories = Category.objects.filter(name__in=categories) # we  convert list of strings into a list of actual category objects, so that we can access all their fields in the template.


        if 'q' in request.GET:  #if in the request.get we have q(name for the search field in form)
            query = request.GET['q'] #we generate variable with that content
            if not query: #if no query variable created
                messages.error(request, 'You did not enter any search criteria!') #return messages
                return redirect(reverse('product')) #and redirect to product page

            queries = Q(name__icontains=query) | Q(description__icontains=query) #creating or logic if query variable is found in either name or description return it
            products = products.filter(queries) #adding queries to the filter

    
    current_sorting = f'{sort}_{direction}'
 
    context = { #make products available in template
        'products': products,
        'search_term': query, #search term is either the empty query or the request.get generated one
        'current_categories': categories,
        'current_sorting' : current_sorting
    }

    return render(request, 'products/products.html', context) #context needed to add to database later on


def product_detail(request, product_id):
    '''a view to return specific product details'''

    product = get_object_or_404(Product, pk=product_id) #return specifi product based on id
 
    context = { #make products available in template
        'product': product
    }

    return render(request, 'products/product_details.html', context) #context needed to add to database later on


@login_required
def add_product(request):
    """ Add product to store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry only store owners can do that')
        return redirect(reverse('home'))
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid')
    else:
        form = ProductForm()
        
    template = 'products/add_product.html'
    context = {
            'form': form
        }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """Edit a product"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry only store owners can do that')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid:
            form.save()
            messages.success(request, f'Product succesfully updated')
            return redirect(reverse('product_detail', args=[product.id]))
        else: 
            messages.error(request, f'Failed to update products, ensure thast all fields are correctly filled in')
    else:
        form = ProductForm(instance=product)
        messages.info(request,f'You are editing{product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry only store owners can do that')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, f'Item has been deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends 'base.html' %} 
{% load static %}


{% block page-header %}
<div class=" container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Add a Product</h5>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <form action="{% url 'add_product' %}" method="POST" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy}}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0">
                        Cancel
                    </a>
                    <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}


{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function(){
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        })
    </script>

{% endblock %}

products/templates/products/edit_product.html
{% extends 'base.html' %} 
{% load static %}


{% block page-header %}
<div class=" container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Edit a Product</h5>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <form action="{% url 'edit_product' product.id %}" method="POST" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy}}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0">
                        Cancel
                    </a>
                    <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('new-image').change(function(){
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: $(file.name)`);
        })
    </script>
{% endblock %} 

products/templates/products/product_details.html
{% extends 'base.html' %}

{% load static %}

{% block page-header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-image-top img-fluid">
                </a>
                {% else %}
                <a href="">
                    <img src="{{ MEDIA_URL }}.noimage.png" alt="{{ product.name }}" class="card-image-top img-fluid">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                <p class="mb-0">{{ product.name }}</p>
                <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a href="{% url 'products' %}?category={{ product.category.name }}" <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                
                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }}</small> {% else %}
                <small class="text-muted">No rating</small>
                {% endif %}
                {% if request.user.is_superuser %}
                    <small class="ml-e">
                        <a href="{% url 'edit_product' product.id%}">Edit</a>
                        <a href="{% url 'delete_product' product.id%}">Delete</a>
                    </small>
                {% endif %}
                <p class="mt-3">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                    {% with product.has_sizes as s %} <!--assign product.has_sizes to variable s-->
                    {% if s %} 
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select name="product_size" id="id_product_size" class="form-control rounded-0 w-50">
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        </div>
                    {% endif %}
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-black rounded-0"
                                                data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                        </button>
                                    </div>
                                    <input type="number" name="quantity" class="form-control qty_input" 
                                        value="1" min="1" max="99" data-item-id="{{ product.id }}"
                                        id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-black rounded-0"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep shopping</span>
                            </a>
                            <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add To Bag">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        <!--Finally, there's a hidden input field here which uses the request.path attribute To submit a field named redirect_url. Which will contain the current URL. By sending the current URL to the view we'll post this form too. We can redirect the user back to the same page once the product is added to their bag.-->
                    {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}